apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::927622788997:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-150EK7C19NAPV
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::927622788997:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-01T06:58:54Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1468"
  uid: 8961f4a9-6fda-42b1-9033-0ebd02c098aa
